# HOWTO: https://pre-commit.com/#usage
# pip3 install pre-commit
# pre-commit install -t pre-commit -t pre-push

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        exclude: archetypes|docs|data|layouts|resources|static|themes/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: https://github.com/packit/pre-commit-hooks
    rev: 1da916777f5cc26ecf221b15e58ca51891d26d94
    hooks:
      - id: check-rebase
        args:
          - https://github.com/packit/packit.dev.git
        stages: [manual, push]
